/*
 * Ski Data API for NEU Seattle distributed systems course
 * An API for an emulation of skier managment system for RFID tagged lift tickets. Basis for CS6650 Assignments for 2019
 *
 * OpenAPI spec version: 1.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.model.LiftRide;
import io.swagger.client.model.ResponseMsg;
import io.swagger.client.model.SkierVertical;
import java.util.Arrays;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SkiersApi
 */
@Ignore
public class SkiersApiTest {

    private final SkiersApi api = new SkiersApi();

    /**
     * 
     *
     * get the total vertical for the skier for the specified ski day
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSkierDayVerticalTest() throws ApiException {
        String resortID = "vail";
        String dayID = "20";
        String skierID = "30";
        SkierVertical response = api.getSkierDayVertical(resortID, dayID, skierID);
        System.out.println(response);
        // TODO: test validations
    }
    /**
     * get the total vertical for the skier for the specified resort
     *
     * get the total vertical for the skier the specified resort.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSkierResortTotalsTest() throws ApiException {
        String skierID = "20";
        List<String> resort = new ArrayList<>(Arrays.asList("vail", "park city"));
        SkierVertical response = api.getSkierResortTotals(skierID, resort);
        System.out.println(response);
        // TODO: test validations
    }
    /**
     * write a new lift ride for the skier
     *
     * Stores new lift ride details in the data store
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void writeNewLiftRideTest() throws ApiException {
        LiftRide body = new LiftRide("vail", "20", "1", "120", "30");
        ApiResponse<Void> response = api.writeNewLiftRideWithHttpInfo(body);
        System.out.println(response.getStatusCode());

        // TODO: test validations
    }
}
